# vim: set ft=yaml ts=2 sw=2 et:
version: '3'
services:

  web:
    container_name: web
    build:
      context: ./docker
      args:
        - USER_NAME=$USER_NAME
        - USER_UID=$USER_UID
        - USER_GID=$USER_GID

    volumes:
      - "$PWD/etc:/etc:ro"
      - "$GOPATH/bin:/bin:ro"
    environment:
      - PORT
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sancus.rule=Host(`@@HOSTNAME@@`)"
      - "traefik.http.services.sancus-service.loadbalancer.server.port=${PORT}"

    networks:
      - @@TRAEFIKNET@@

networks:
  @@TRAEFIKNET@@:
    external: true
